file = {'lualib/rfold/protein.lua', 'lualib/rfold/chain.lua', 'lualib/rfold/residue.lua', 'lualib/rfold/dihedron.lua', 'lualib/rfold/hedron.lua', 'lualib/rfold/geom3d.lua', 'lualib/rfold/parsers.lua', 'lualib/rfold/utils.lua' }
project = "rFold"
title = 'rFold reference'
description = "Lua modules to create, manipulate and analyse three-dimensional protein structures"
full_description = ""
format = 'markdown'
readme = "README.md"
examples = {'build/buildProtein.lua'}
boilerplate = true

